export const ActionTypes = {
  LOGIN_STARTED: 'LOGIN_STARTED',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOADING: 'LOADING',
  FETCH_GLOBAL: 'FETCH_GLOBAL',
  FETCH_SUCCESS_END: 'FETCH_SUCCESS',
  FETCH_FAIL: 'FETCH_FAIL',
  FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
  NEW_TASK_SUCCESS: 'NEW_TASK_SUCCESS',
  BOT_SUCCESS: 'BOT_SUCCESS',
  ACC_SUCCESS: 'ACC_SUCCESS',
};
